FROM golang:1.25.1-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o worker .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/worker .
EXPOSE 8081
CMD ["./worker"]
