apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - backend-pdb.yaml
  - worker-deployment.yaml
  - worker-service.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - minio-pvc.yaml
